### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by wilderav86**
Okay. Dis the homework. 

I'm not sure if i should have only moved the .css .html and .js files or the whole nodeapps folder since the folder contains the img i used in the changes, so I opted for the whole folder. 

lemme know if correct or convoluted.

### CODE REVIEW

**Comment by manbradcalf** [comment]
this looks great hoss, but go ahead and delete the `nodeapps/` directory you have so we don't have duplicate files. ya dig

**Comment by wilderav86** [comment]
I dig. Was gonna do it last night but went into food coma. Will do tonight
for sure.

**Comment by wilderav86** [comment]
ok folder gone. I created a folder for the image i used in case we want to add anymore images in the future. Is that thinking correct or should I have just added the image file?

**Comment by manbradcalf** [comment]
> ok folder gone. I created a folder for the image i used in case we want to add anymore images in the future. Is that thinking correct or should I have just added the image file?

Yeah that's a good idea, I would have probably done the same. But really it just comes down to how you want to structure your "working directory", aka all your files.

**Pull request merged**
